#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: '$y$j9T$gE.SfpQCKHgcndlATr8xb1$CnqXkcLSXZ1ajIeE3MRByUz9NpjcOJVIAAMv0y3Pa6.'
    lock_passwd: false
    shell: /bin/bash
package_update: true
package_upgrade: true
packages:
  - fail2ban
  - ufw
  - xfce4
  - firefox
runcmd:
  - wget https://download.nomachine.com/download/8.5/Linux/nomachine_8.5.3_1_amd64.deb
  - sudo dpkg -i nomachine_8.5.3_1_amd64.deb
  - sudo /etc/NX/nxserver --restart
  - sudo ufw allow 4000
  - cd /home/devops/ && wget https://www.torproject.org/dist/torbrowser/12.0.7/tor-browser-linux64-12.0.7_ALL.tar.xz && tar -xf ./tor-browser-linux64-12.0.7_ALL.tar.xz && chown -R devops:devops tor-browser
  - sudo reboot